# Atelier Numpy

## Partie 1:

### Importation du module Numpy

In [56]:
import numpy as np

### Création du listes python stockant ces températures

In [57]:
temperature_listes = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperature_listes)

[24.5, 25.1, 26.3, 27.0, 25.8]


### Création du tableau NumPy équivalent stockant ces températures 

In [58]:
temperature_listes_np = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperature_listes_np)

[24.5 25.1 26.3 27.  25.8]


###  Multiplication par 2 sur ces deux collections

In [59]:
resultat_listes = temperature_listes * 2
print(resultat_listes)

resultat_listes_np = temperature_listes_np * 2
print(resultat_listes_np)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


###  Différence que l'on observe

- Avec la **liste Python**, l'opérateur `*` duplique la liste : les 5 éléments sont répétés deux fois, ce qui donne une liste de 10 éléments.
- Avec le **tableau NumPy**, l'opérateur `*` effectue une multiplication mathématique élément par élément : chaque température est multipliée par 2, ce qui donne un tableau de 5 éléments (les valeurs doublées).

Cela montre que NumPy permet des opérations **vectorisées** (calcul mathématique direct sur toutes les valeurs), contrairement aux listes Python qui traitent les opérateurs de façon littérale (concaténation/répétition).

## Partie 2:

### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [60]:
capteurs_zero = np.zeros(10)
print(capteurs_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [61]:
capteurs_un = np.ones(10)
print(capteurs_un)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3) Créer un tableau de 10 valeurs initialisées à 25. 

In [62]:
capteur_25 = np.full(10,25)
print(capteur_25)

[25 25 25 25 25 25 25 25 25 25]


### 4) Créer une matrice identité de taille 5 × 5. 

In [63]:
identite = np.eye(5)
print(identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [64]:
heures = np.arange(0,24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [65]:
temperature_reparties = np.linspace(20,30,10)
print(temperature_reparties)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [66]:
np.random.seed(42)
temperature_aleatoires = np.random.uniform(15,35,100)
print(temperature_aleatoires)

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687
 24.12139968 30.70351923 18.99347564 25.28468877 26.84829138 15.92900825
 27.15089704 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696
 21.09227538 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382
 15.68777042 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042
 25.93420559 18.69708911 34.39169256 30.50265647 33.78997883 32.89654701
 26.95799958 33.4374847  16.76985004 18.91965725 15.90454578 21.50660662
 22.77354579 20.42698064 31.57475018 22.13506653 20.61869019 25.85392166
 17.8184845  31.04393962 16.49101287 34.73773873 30.44489539 18.97431363
 15.11044234 31.30922857 29.13714688 29.58014336 30.42540693 16.48089303
 22.16931457 17.31738119 32.26206852 27.46596254 21.

## Partie 3 – Exploration des tableaux

### 1) Créer aléatoirement un tableau représentant les 24 températures d'une journée :

In [67]:
np.random.seed(42)
temperature_jour = np.random.uniform(15,35,24)
print(temperature_jour)

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]


### 2) Déterminer les propriétés suivantes du tableau 

#### a) nombre de dimensions ;  

In [68]:
nombre_dim = print(temperature_jour.ndim)

1


 #### b) nombre de valeurs ; 

In [69]:
nombre_valeur = print(temperature_jour.size)

24


#### c) type des données ; 

In [70]:
type_donnee = print(temperature_jour.dtype)

float64


#### d) forme du tableau.

In [71]:
forme_tableau = print(temperature_jour.shape)

(24,)


## Partie 4 – Indexation et slicing

#### Considérant le tableau représentant les 24 températures d'une journée, afficher : 
#### 1) la première mesure ;  

In [72]:
premier_mesure = temperature_jour[0]
print(premier_mesure)

22.49080237694725


#### 2) la dernière mesure ;  

In [73]:
dernier_mesure = temperature_jour[-1]
print(dernier_mesure)

22.327236865873836


#### 3) la température de 8h ;

In [74]:
print(temperature_jour[8])

27.022300234864176


#### 4) les températures de 8h à 12h ;

In [75]:
print(temperature_jour[8:13])

[27.02230023 29.16145156 15.41168989 34.39819704 31.64885282]


#### 5) les températures des 6 premières heures ; 

In [76]:
print(temperature_jour[0:6])

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041]


#### 6) les températures des heures paires. 

In [77]:
print(temperature_jour[0::2])

[22.49080238 29.63987884 18.12037281 16.16167224 27.02230023 15.41168989
 31.64885282 18.63649934 21.08484486 23.63890037 27.23705789 20.84289297]


## Partie 5 – Filtrage booléen 

#### Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les situations inhabituelles.  
#### 1) Afficher les températures supérieures à 30 °C

In [78]:
print(temperature_jour > 30)

print(temperature_jour[temperature_jour > 30])

[False  True False False False False False  True False False False  True
  True False False False False False False False False False False False]
[34.01428613 32.32352292 34.39819704 31.64885282]


#### 2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [79]:
temperature_jour_normales = temperature_jour[(temperature_jour >= 20) & (temperature_jour <= 30)]
print(temperature_jour_normales)

[22.49080238 29.63987884 26.97316968 27.02230023 29.16145156 21.08484486
 25.49512863 23.63890037 20.8245828  27.23705789 20.84289297 22.32723687]


#### 3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. Déterminer anomalies, un tableau de booléen précisant les anomalies 

In [80]:
anomalies = temperature_jour>35
print(anomalies)

[False False False False False False False False False False False False
 False False False False False False False False False False False False]


#### 4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies 

In [81]:
nombre_anomalies = np.sum(anomalies)
print(nombre_anomalies)

0


## Partie 6 – Manipulation des dimensions 

#### On suppose qu’on a 5 capteurs.  
#### 1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée 

In [82]:
np.random.uniform(42)
temperature_capteurs = np.random.uniform(15,35,(5,24))
print(temperature_capteurs)

[[30.70351923 18.99347564 25.28468877 26.84829138 15.92900825 27.15089704
  18.41048247 16.30103186 33.97771075 34.31264066 31.16794696 21.09227538
  16.95344228 28.68466053 23.80304987 17.4407647  24.9035382  15.68777042
  33.18640804 20.17559963 28.25044569 21.23422152 25.40136042 25.93420559]
 [18.69708911 34.39169256 30.50265647 33.78997883 32.89654701 26.95799958
  33.4374847  16.76985004 18.91965725 15.90454578 21.50660662 22.77354579
  20.42698064 31.57475018 22.13506653 20.61869019 25.85392166 17.8184845
  31.04393962 16.49101287 34.73773873 30.44489539 18.97431363 15.11044234]
 [31.30922857 29.13714688 29.58014336 30.42540693 16.48089303 22.16931457
  17.31738119 32.26206852 27.46596254 21.6179605  16.27116701 21.21964643
  21.50366644 29.59212357 27.75114943 32.74425485 24.4442985  17.39188492
  29.26489574 30.21570097 26.22554395 30.4193436  24.87591193 25.45465659]
 [23.55082037 15.50838253 17.15782854 15.62858371 27.72820823 21.28711962
  25.17141382 33.15132948 19.9858445

#### 2) Transformer la matrice en un tableau unidimensionnel 

In [83]:
temperature_capteurs_flat = temperature_capteurs.flatten()
print(temperature_capteurs_flat)
print(temperature_capteurs_flat.shape)

[30.70351923 18.99347564 25.28468877 26.84829138 15.92900825 27.15089704
 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696 21.09227538
 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382  15.68777042
 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042 25.93420559
 18.69708911 34.39169256 30.50265647 33.78997883 32.89654701 26.95799958
 33.4374847  16.76985004 18.91965725 15.90454578 21.50660662 22.77354579
 20.42698064 31.57475018 22.13506653 20.61869019 25.85392166 17.8184845
 31.04393962 16.49101287 34.73773873 30.44489539 18.97431363 15.11044234
 31.30922857 29.13714688 29.58014336 30.42540693 16.48089303 22.16931457
 17.31738119 32.26206852 27.46596254 21.6179605  16.27116701 21.21964643
 21.50366644 29.59212357 27.75114943 32.74425485 24.4442985  17.39188492
 29.26489574 30.21570097 26.22554395 30.4193436  24.87591193 25.45465659
 23.55082037 15.50838253 17.15782854 15.62858371 27.72820823 21.28711962
 25.17141382 33.15132948 19.98584458 23.20765846 30.

#### 3) Déterminer la transposée de la matrice 

In [86]:
temperature_transposee = temperature_capteurs.T
print(temperature_transposee)
print(temperature_transposee.shape)

[[30.70351923 18.69708911 31.30922857 23.55082037 32.921826  ]
 [18.99347564 34.39169256 29.13714688 15.50838253 21.3600695 ]
 [25.28468877 30.50265647 29.58014336 17.15782854 17.20103849]
 [26.84829138 33.78997883 30.42540693 15.62858371 19.55870325]
 [15.92900825 32.89654701 16.48089303 27.72820823 23.54215577]
 [27.15089704 26.95799958 22.16931457 21.28711962 31.36029532]
 [18.41048247 33.4374847  17.31738119 25.17141382 32.21461167]
 [16.30103186 16.76985004 32.26206852 33.15132948 15.13904261]
 [33.97771075 18.91965725 27.46596254 19.98584458 25.21494605]
 [34.31264066 15.90454578 21.6179605  23.20765846 23.34822006]
 [31.16794696 21.50660662 16.27116701 30.11102277 19.44215621]
 [21.09227538 22.77354579 21.21964643 19.57596331 17.39730735]
 [16.95344228 20.42698064 21.50366644 16.5395982  21.75230343]
 [28.68466053 31.57475018 29.59212357 20.79502906 33.85819408]
 [23.80304987 22.13506653 27.75114943 18.22442575 21.46405864]
 [17.4407647  20.61869019 32.74425485 33.59395305 25.37

#### 4) Extraire toutes les mesures du capteur 1 ; 

In [87]:
capteur_1 = temperature_capteurs[0]
print(capteur_1)

[30.70351923 18.99347564 25.28468877 26.84829138 15.92900825 27.15089704
 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696 21.09227538
 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382  15.68777042
 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042 25.93420559]


#### 5) Extraire toutes les mesures du capteur 5 ;

In [88]:
capteur_5 = temperature_capteurs[4]
print(capteur_5)

[32.921826   21.3600695  17.20103849 19.55870325 23.54215577 31.36029532
 32.21461167 15.13904261 25.21494605 23.34822006 19.44215621 17.39730735
 21.75230343 33.85819408 21.46405864 25.37581243 29.06037918 22.27259205
 34.43564165 34.2489459  20.03564592 24.94497012 21.0175662  20.69680989]


#### 6) Extraire les mesures de tous les capteurs à 10h ;

In [89]:
mesures_10h = temperature_capteurs[:,10]
print(mesures_10h)

[31.16794696 21.50660662 16.27116701 30.11102277 19.44215621]


#### 7) Extraire les mesures des capteurs 2 à 4 entre 8h et 12h. 

In [90]:
extrait = temperature_capteurs[1:4, 8:13]
print(extrait)
print(extrait.shape)

[[18.91965725 15.90454578 21.50660662 22.77354579 20.42698064]
 [27.46596254 21.6179605  16.27116701 21.21964643 21.50366644]
 [19.98584458 23.20765846 30.11102277 19.57596331 16.5395982 ]]
(3, 5)


## Partie 7 – Concaténation 

#### On suppose qu’on a un 2nd bâtiment avec 3 capteurs.  
#### 1) Créer aléatoirement la matrice représentant les températures mesurées par les 3 capteurs durant une journée

In [92]:
np.random.seed(42)
temperature_batiment2 = np.random.uniform(15, 35, (3, 24))
print(temperature_batiment2)
print(temperature_batiment2.shape)

[[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
  16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
  31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
  23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]
 [24.12139968 30.70351923 18.99347564 25.28468877 26.84829138 15.92900825
  27.15089704 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696
  21.09227538 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382
  15.68777042 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042]
 [25.93420559 18.69708911 34.39169256 30.50265647 33.78997883 32.89654701
  26.95799958 33.4374847  16.76985004 18.91965725 15.90454578 21.50660662
  22.77354579 20.42698064 31.57475018 22.13506653 20.61869019 25.85392166
  17.8184845  31.04393962 16.49101287 34.73773873 30.44489539 18.97431363]]
(3, 24)


#### 2) Déterminer de deux manières différentes la matrice qui fusionne les températures mesurées par les 8 capteurs durant une journée 

##### Méthode 1 — avec np.concatenate()

In [93]:
tous_capteurs_v1 = np.concatenate((temperature_capteurs, temperature_batiment2), axis=0)
print(tous_capteurs_v1.shape)

(8, 24)


##### Méthode 2 — avec np.vstack()

In [94]:
tous_capteurs_v2 = np.vstack((temperature_capteurs, temperature_batiment2))
print(tous_capteurs_v2.shape)

(8, 24)


## Partie 8 : Calcul scientifique 

#### Considérons le tableau représentant les 24 températures du 1er bâtiment. 
#### 1) Pour les températures calculer le minimum, le maximum, la somme, la moyenne, la médiane, la variance et l’écart-type 

In [95]:
minimum = np.min(temperature_jour)
maximum = np.max(temperature_jour)
somme = np.sum(temperature_jour)
moyenne = np.mean(temperature_jour)
mediane = np.median(temperature_jour)
variance = np.var(temperature_jour)
ecart_type = np.std(temperature_jour)

print("Min :", minimum)
print("Max :", maximum)
print("Somme :", somme)
print("Moyenne :", moyenne)
print("Médiane :", mediane)
print("Variance :", variance)
print("Écart-type :", ecart_type)

Min : 15.411689885916049
Max : 34.39819704323989
Somme : 571.2779803031808
Moyenne : 23.8032491792992
Médiane : 22.409019621410543
Variance : 32.53568144079373
Écart-type : 5.7040057363920775


#### 2) Standardiser le tableau des températures puis vérifier les valeurs de la moyenne et de l’écarttype du tableau standardisé

In [100]:
temperature_standardisees = (temperature_jour - moyenne) / ecart_type
print(temperature_standardisees)

print("Nouvelle moyenne :", np.mean(temperature_standardisees))
print("Nouvel écart-type :", np.std(temperature_standardisees))

[-0.23009213  1.79015194  1.02325101  0.55573585 -0.9962957  -0.99638027
 -1.33968605  1.49373513  0.5643492   0.93937535 -1.4711695   1.85745743
  1.37545507 -0.79881879 -0.90581077 -0.90027241 -0.47657812  0.29661251
 -0.02881288 -0.52220606  0.60199952 -1.05423666 -0.51899601 -0.25876768]
Nouvelle moyenne : 1.4802973661668753e-16
Nouvel écart-type : 1.0


#### 3) Normaliser (Min-Max) le tableau des températures puis vérifier les valeurs du tableau normalisé

In [99]:
temperature_normalisees = (temperature_jour - minimum) / (maximum - minimum)
print(temperature_normalisees)

print("Min du tableau normalisé :", np.min(temperature_normalisees))
print("Max du tableau normalisé :", np.max(temperature_normalisees))

[0.37284965 0.9797798  0.74938422 0.60893137 0.14266357 0.14263816
 0.03950081 0.89072903 0.61151903 0.72418595 0.         1.
 0.85519484 0.20199041 0.16984743 0.17151129 0.2987993  0.53108445
 0.4333188  0.28509156 0.62283009 0.12525671 0.28605594 0.36423482]
Min du tableau normalisé : 0.0
Max du tableau normalisé : 1.0


#### 4) Convertir le tableau initial en Fahrenheit 

In [101]:
temperature_fahrenheit = temperature_jour * 9/5 + 32
print(temperature_fahrenheit)

[72.48344428 93.22571503 85.35178191 80.55170543 64.61667106 64.61580273
 61.09101004 90.18234125 80.64014042 84.4906128  59.74104179 93.91675468
 88.96793507 66.64420798 65.54569882 65.60256235 69.95272075 77.89123154
 74.55002067 69.48424905 81.02670421 64.02177898 69.51720735 72.18902636]
