# Atelier Numpy

## Partie 1:

### Importation du module Numpy

In [1]:
import numpy as np

### Création du listes python stockant ces températures

In [3]:
temperature_listes = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperature_listes)

[24.5, 25.1, 26.3, 27.0, 25.8]


### Création du tableau NumPy équivalent stockant ces températures 

In [4]:
temperature_listes_np = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperature_listes_np)

[24.5 25.1 26.3 27.  25.8]


###  Multiplication par 2 sur ces deux collections

In [5]:
resultat_listes = temperature_listes * 2
print(resultat_listes)

resultat_listes_np = temperature_listes_np * 2
print(resultat_listes_np)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


###  Différence que l'on observe

- Avec la **liste Python**, l'opérateur `*` duplique la liste : les 5 éléments sont répétés deux fois, ce qui donne une liste de 10 éléments.
- Avec le **tableau NumPy**, l'opérateur `*` effectue une multiplication mathématique élément par élément : chaque température est multipliée par 2, ce qui donne un tableau de 5 éléments (les valeurs doublées).

Cela montre que NumPy permet des opérations **vectorisées** (calcul mathématique direct sur toutes les valeurs), contrairement aux listes Python qui traitent les opérateurs de façon littérale (concaténation/répétition).

## Partie 2:

### 1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [6]:
capteurs_zero = np.zeros(10)
print(capteurs_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2) Créer un tableau contenant 10 valeurs égales à 1. 

In [8]:
capteurs_un = np.ones(10)
print(capteurs_un)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3) Créer un tableau de 10 valeurs initialisées à 25. 

In [7]:
capteur_25 = np.full(10,25)
print(capteur_25)

[25 25 25 25 25 25 25 25 25 25]


### 4) Créer une matrice identité de taille 5 × 5. 

In [9]:
identite = np.eye(5)
print(identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5) Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [10]:
heures = np.arange(0,24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [11]:
temperature_reparties = np.linspace(20,30,10)
print(temperature_reparties)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [12]:
np.random.seed(42)
temperature_aleatoires = np.random.uniform(15,35,100)
print(temperature_aleatoires)

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687
 24.12139968 30.70351923 18.99347564 25.28468877 26.84829138 15.92900825
 27.15089704 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696
 21.09227538 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382
 15.68777042 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042
 25.93420559 18.69708911 34.39169256 30.50265647 33.78997883 32.89654701
 26.95799958 33.4374847  16.76985004 18.91965725 15.90454578 21.50660662
 22.77354579 20.42698064 31.57475018 22.13506653 20.61869019 25.85392166
 17.8184845  31.04393962 16.49101287 34.73773873 30.44489539 18.97431363
 15.11044234 31.30922857 29.13714688 29.58014336 30.42540693 16.48089303
 22.16931457 17.31738119 32.26206852 27.46596254 21.